apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "manticoresearch.fullname" . }}-balancer-config
  labels:
    {{- include "manticoresearch.componentLabels" (list "balancer" .) | nindent 4 }}
data:
  manticore.conf:
    {{ toYaml .Values.balancer.config.content | indent 4 }}

