apiVersion: v1
kind: Service
metadata:
  name: {{ include "manticoresearch.fullname" . }}-balancer-svc
  labels:
    name: {{ include "manticoresearch.fullname" . }}-balancer-svc
    {{- include "manticoresearch.componentLabels" (list "balancer" .) | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.balancer.service.ql.port }}
    targetPort: {{ .Values.balancer.service.ql.targetPort }}
    name: balancer
  - port: {{ .Values.balancer.service.observer.port }}
    targetPort: {{ .Values.balancer.service.observer.targetPort }}
    name: observer
  - port: {{ .Values.balancer.service.http.port }}
    targetPort: {{ .Values.balancer.service.http.targetPort }}
    name: http
  {{- if and .Values.exporter.enabled .Values.exporter.serviceMonitor }}
  - port: {{ .Values.exporter.port }}
    targetPort: {{ .Values.exporter.port }}
    name: monitoring
  {{- end }}
  selector:
    {{- include "manticoresearch.componentSelectorLabels" (list "balancer" .) | nindent 4 }}
