apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "manticoresearch.fullname" . }}-worker-config
  labels:
    {{- include "manticoresearch.componentLabels" (list "worker" .) | nindent 4 }}
data:
  manticore.conf:
    {{ toYaml .Values.worker.config.content | indent 4 }}
